default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', nil) %>

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", nil) %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE", nil) %>
  host: <%= ENV.fetch("DATABASE_HOST", nil) %>
  pool: 5
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  port: <%= ENV.fetch("DATABASE_PORT", nil) %>

